let nombre1=prompt("Entrez un nombre","")
let nombre2=prompt("Entrez un nombre","")
let nombre3=prompt("Entrez un nombre", "")
let max=Math.max(nombre1,nombre2,nombre3)
console.log(`[${nombre1},${nombre2},${nombre3}]=>${max}`)